# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 445b653cdb78031bda129321aefc2dbd60e40864a5d524a08f091240d0878d396a5bca6afef39bf4730db41e942dd5e70eafe6e03037b1761dfa5be0a055ba4f

test:
  secret_key_base: ddc1a5f65b56b21fa35bfcfdb11239ba5fdbb945cdbf2df13c97525610b0f9ab92b3a532bc0763f246c933304977f396237fdb4e031928d27db6fee97b599c64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
